"use client";
import { useEffect, useRef, useState } from "react";
import { Bell, Check, CloudDownload, Database, Download, FileJson, FileSpreadsheet, FileText, MonitorCog, Pause, Play, RotateCcw, Save, Smartphone, Upload } from "lucide-react";
import { PageIntro } from "@/src/components/ui";
import type { LifeHubData, Profile, ThemeName } from "@/src/entities/types";
import { selectLifeHubData, useLifeHubStore } from "@/src/store/use-lifehub-store";
import { formatMoney, quitStats } from "@/src/utils/calculations";
import { requestNotificationPermission, showDailyReminder } from "@/src/services/pwa";

const themes: { id: ThemeName; title: string; colors: string[]; text: string }[] = [
  { id: "light", title: "Светлая", colors: ["#f5f8f4", "#1b493d", "#74c9a3"], text: "Чистый дневной свет" },
  { id: "dark", title: "Тёмная", colors: ["#071d19", "#dff8ed", "#54d29b"], text: "Глубокий спокойный фон" },
  { id: "system", title: "Системная", colors: ["#eeeeee", "#18241f", "#6dcda6"], text: "Следует настройкам устройства" },
  { id: "nature", title: "Природа", colors: ["#e8f0df", "#355c3d", "#db9f5c"], text: "Тёплый луг и земля" },
  { id: "forest", title: "Лес", colors: ["#0a241c", "#d8e9ce", "#94bd62"], text: "Хвойная глубина" },
  { id: "sea", title: "Море", colors: ["#062a34", "#d7f5f4", "#54c7cb"], text: "Свежая морская палитра" },
  { id: "sky", title: "Небо", colors: ["#eaf4ff", "#254265", "#78aeea"], text: "Воздух и ясность" },
];

type InstallPrompt = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> };

export default function SettingsPage() {
  const state = useLifeHubStore();
  const [profile, setProfile] = useState<Profile>(state.profile!);
  const [message, setMessage] = useState("");
  const [installPrompt, setInstallPrompt] = useState<InstallPrompt | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => { const handler = (event: Event) => { event.preventDefault(); setInstallPrompt(event as InstallPrompt); }; window.addEventListener("beforeinstallprompt", handler); return () => window.removeEventListener("beforeinstallprompt", handler); }, []);
  const snapshot = (): LifeHubData => selectLifeHubData(useLifeHubStore.getState());
  const download = (name: string, body: BlobPart, type: string) => { const url = URL.createObjectURL(new Blob([body], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); setMessage(`Файл ${name} создан`); };
  const exportJson = () => download(`lifehub-backup-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify({ format: "lifehub-backup", version: 1, exportedAt: new Date().toISOString(), data: snapshot() }, null, 2), "application/json");
  const exportCsv = () => { const rows = [["Тип", "Дата", "Показатель", "Триггер/заметка"], ...state.cravings.map((i) => ["Тяга", i.at, i.intensity, i.trigger]), ...state.moods.map((i) => ["Настроение", i.at, i.score, i.note]), ...state.relapses.map((i) => ["Срыв", i.at, i.amount, i.trigger]), ...state.activity.map((i) => ["Активность", i.date, i.xp, i.tasks.join("; ")])]; const csv = "\uFEFF" + rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(";")).join("\n"); download(`lifehub-data-${new Date().toISOString().slice(0, 10)}.csv`, csv, "text/csv;charset=utf-8"); };
  const exportPdf = async () => { const { jsPDF } = await import("jspdf"); const stats = quitStats(state.profile); const doc = new jsPDF(); doc.setFont("helvetica", "bold"); doc.setFontSize(22); doc.text("LIFEHUB", 20, 24); doc.setFontSize(13); doc.text("Personal progress report", 20, 34); doc.setFont("helvetica", "normal"); const lines = [`Days: ${stats.days}`, `Smoke-free units: ${stats.cigarettes}`, `Saved: ${formatMoney(stats.saved).replace(/[^0-9,.]/g, "")} RUB`, `Program days: ${state.completedDays.length}/365`, `Current streak: ${state.streak}`, `XP: ${state.xp}`, `Craving records: ${state.cravings.length}`, `Mood records: ${state.moods.length}`, `Forest objects: ${state.forest.length}`]; lines.forEach((line, index) => doc.text(line, 20, 50 + index * 9)); doc.setFontSize(9); doc.text("Educational wellbeing tracker. Data exported from local IndexedDB.", 20, 145); doc.save(`lifehub-report-${new Date().toISOString().slice(0, 10)}.pdf`); setMessage("PDF-отчёт создан"); };
  const importJson = async (file?: File) => { if (!file) return; try { const parsed = JSON.parse(await file.text()); const data = (parsed.data ?? parsed) as LifeHubData; if (!data.profile || !Array.isArray(data.completedDays) || !Array.isArray(data.cravings)) throw new Error("invalid"); await state.importData(data); setProfile(data.profile); setMessage("Данные полностью восстановлены"); } catch { setMessage("Не удалось импортировать: файл не похож на резервную копию LifeHub"); } finally { if (fileRef.current) fileRef.current.value = ""; } };
  const toggleNotifications = async (enabled: boolean) => {
    if (!enabled) { state.setNotifications(false); setMessage("Системные напоминания выключены. Внутренний список задач остаётся доступен по колокольчику."); return; }
    const allowed = await requestNotificationPermission();
    state.setNotifications(allowed);
    if (allowed) { await showDailyReminder(state.activeDay); setMessage("Напоминания включены"); }
    else setMessage("Браузер не дал разрешение. Задачи по-прежнему будут видны внутри LifeHub.");
  };
  return <div className="page-stack"><PageIntro eyebrow="Приложение подстраивается под вас" title="Настройки" text="Темы, доступность, профиль и полная переносимость локальных данных." />
    {message && <div className="toast-inline" role="status"><Check />{message}<button onClick={() => setMessage("")}>Закрыть</button></div>}
    <section className="section-card settings-section"><header><div><span className="eyebrow">Внешний вид</span><h3>Тема интерфейса</h3></div><MonitorCog /></header><div className="theme-grid">{themes.map((item) => <button key={item.id} className={state.theme === item.id ? "active" : ""} onClick={() => state.setTheme(item.id)}><div>{item.colors.map((color) => <i key={color} style={{ background: color }} />)}</div><span><b>{item.title}</b><small>{item.text}</small></span>{state.theme === item.id && <Check />}</button>)}</div><div className="setting-row"><span><b>Уменьшить анимацию</b><small>Отключает декоративное движение и быстрые переходы</small></span><label className="switch"><span className="sr-only">Уменьшить анимацию</span><input type="checkbox" checked={state.reducedMotion} onChange={(e) => state.setReducedMotion(e.target.checked)} /><i /></label></div></section>
    <section className="section-card settings-section"><header><div><span className="eyebrow">Профиль и расчёты</span><h3>Ваша точка отсчёта</h3></div><Database /></header><div className="form-grid"><label>Имя<input value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} /></label><label>Тип никотина<select value={profile.nicotineType} onChange={(e) => setProfile({ ...profile, nicotineType: e.target.value as Profile["nicotineType"] })}>{["Сигареты", "Вейп", "Снюс", "Нагревание табака", "Другое"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="full">Дата отказа<input type="datetime-local" value={new Date(new Date(profile.quitAt).getTime() - new Date(profile.quitAt).getTimezoneOffset() * 60000).toISOString().slice(0, 16)} onChange={(e) => setProfile({ ...profile, quitAt: new Date(e.target.value).toISOString() })} /></label><label>В день<input type="number" min="1" value={profile.cigarettesPerDay} onChange={(e) => setProfile({ ...profile, cigarettesPerDay: Number(e.target.value) })} /></label><label>В пачке<input type="number" min="1" value={profile.cigarettesPerPack} onChange={(e) => setProfile({ ...profile, cigarettesPerPack: Number(e.target.value) })} /></label><label>Цена пачки, ₽<input list="pack-price-history" type="number" min="0" value={profile.packPrice} onChange={(e) => setProfile({ ...profile, packPrice: Number(e.target.value) })} /><datalist id="pack-price-history">{state.packPriceHistory.map((price) => <option key={price} value={price}>{price} ₽</option>)}</datalist><small>Ранее: {state.packPriceHistory.length ? state.packPriceHistory.map((price) => `${price} ₽`).join(", ") : "цена сохранится после первого изменения"}</small></label><label className="full">Личная причина<textarea rows={3} value={profile.motivation} onChange={(e) => setProfile({ ...profile, motivation: e.target.value })} /></label></div><button className="primary-button" onClick={() => { state.setProfile(profile); setMessage("Профиль и расчёты обновлены. Цена добавлена в историю вариантов."); }}><Save /> Сохранить изменения</button></section>
    <section className="section-card settings-section"><header><div><span className="eyebrow">Ритм</span><h3>Пауза и уведомления</h3></div><Bell /></header><div className="setting-row"><span><b>Пауза в программе</b><small>История сохраняется, активный день не меняется автоматически</small></span><button className="ghost-button" onClick={() => state.setPaused(!state.paused)}>{state.paused ? <Play /> : <Pause />}{state.paused ? "Продолжить" : "Поставить на паузу"}</button></div><div className="setting-row"><span><b>Мягкие напоминания</b><small>Системное уведомление при входе и постоянный список задач по колокольчику</small></span><label className="switch"><span className="sr-only">Мягкие напоминания</span><input type="checkbox" checked={state.notifications} onChange={(e) => void toggleNotifications(e.target.checked)} /><i /></label></div></section>
      <section className="section-card settings-section"><header><div><span className="eyebrow">Переносимость</span><h3>Импорт и экспорт</h3></div><CloudDownload /></header><p>JSON содержит полную резервную копию. CSV удобен для таблиц, PDF — для краткого отчёта.</p><div className="export-grid"><button onClick={exportJson}><FileJson /><span><b>Экспорт JSON</b><small>Полное восстановление</small></span><Download /></button><button onClick={exportCsv}><FileSpreadsheet /><span><b>Экспорт CSV</b><small>Дневники и активность</small></span><Download /></button><button onClick={() => void exportPdf()}><FileText /><span><b>Экспорт PDF</b><small>Краткий отчёт</small></span><Download /></button><button onClick={() => fileRef.current?.click()}><Upload /><span><b>Импорт JSON</b><small>С проверкой структуры</small></span></button></div><input ref={fileRef} className="sr-only" type="file" accept="application/json,.json" onChange={(e) => void importJson(e.target.files?.[0])} /></section>
    <section className="install-card"><Smartphone /><div><span className="eyebrow">PWA · работает офлайн</span><h3>Установите LifeHub на устройство</h3><p>После первой загрузки программа, игры, дневники и библиотека доступны без сети.</p></div><button className="primary-button" onClick={async () => { if (installPrompt) { await installPrompt.prompt(); setInstallPrompt(null); } else setMessage("Откройте меню браузера и выберите «Установить приложение» или «На экран Домой»"); }}>Установить</button></section>
    <section className="danger-zone"><div><RotateCcw /><span><b>Начать с чистого листа</b><small>Это удалит локальные данные после подтверждения. Экспортируйте JSON заранее.</small></span></div><button className="ghost-button danger" onClick={() => { if (window.confirm("Удалить локальный профиль и всю историю LifeHub? Это действие нельзя отменить без резервной копии.")) void state.resetData(); }}>Сбросить данные</button></section>
  </div>;
}
